# Generated by Django 2.1.4 on 2020-01-31 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='notes',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='category',
        ),
    ]
